# Create your own keys & tokens on https://apps.twitter.com/app/new
# and rename this file to config.yml
consumer-key: YOUR_KEY
consumer-secret: YOUR_SECRET
access-token: YOUR_TOKEN
access-secret: YOUR_TOKEN_SECRET
max-mentions: 1
max-tags: 2
lang: en
urls: false
retweets: false
replies: false
via: false
min-followers: 5
min-following: 5