# Create your own keys & tokens on https://apps.twitter.com/app/new
# and rename this file to config.yml
consumer_key: YOUR_KEY
consumer_secret: YOUR_SECRET
access_token: YOUR_TOKEN
access_secret: YOUR_TOKEN_SECRET